#!/bin/sh

##############################################################################
# This script will build a Segue 2 package and put it a ~/Releases directory.
#
# Harmoni and polyphony packages will be built as well and will be copied in to 
# the appropriate places in the Segue package.
#
# 3rd party libraries will also be downloaded from the git repository server
# and copied into the appropriate places.
##############################################################################

segueRepo=/home/afranco/repositories/public/segue-1.x.git

destDir=~/Releases
libraryUrl="http://slug.middlebury.edu/git/libraries/segue-1.x"

usage="Usage: `basename $0` -S <segue tag> \n\t [-s <segue repo>] [-d <dest dir>]"

# Set up options
while getopts ":S:s:d:" options; do
	case $options in
	S ) segueTag=$OPTARG;;
	s ) segueRepo=$OPTARG;;
	d ) destDir=$OPTARG;;
	\? ) echo -e $usage
		exit 1;;
	* ) echo -e $usage
		exit 1;;
	
	esac
done

# Test for Segue Tag
if [  ! -n "$segueTag" ]
then
	echo -e $usage
	exit 1
fi

# Ensure that we have an absolute path
destDir=$(readlink -f $destDir)

if [ ! -e "$destDir" ]
then
	echo "$destDir does not exist."
	echo 
	echo -e $usage
	exit 2
fi

#########################
# Segue
#########################
# Clean up any previous segue builds
if [ -e "$destDir/${segueTag}.zip" ]
then
	rm $destDir/${segueTag}.zip
fi
if [ -e "$destDir/${segueTag}" ]
then
	rm -rf $destDir/${segueTag}
fi

# Export segue
cd $segueRepo
git-archive --format=zip --prefix=${segueTag}/ $segueTag > $destDir/${segueTag}.zip
cd $destDir
unzip -q ${segueTag}.zip
rm ${segueTag}.zip


# Add the audio player libraries
cd $destDir/${segueTag}
wget -q ${libraryUrl}/audio-player.zip
unzip -q audio-player.zip
rm audio-player.zip
cd $destDir

# Add the FCKEditor libraries
cd $destDir/${segueTag}/htmleditor/fckeditor
wget -q ${libraryUrl}/fckeditor.zip
unzip -q fckeditor.zip
rm fckeditor.zip
cd $destDir


# Re-Compress Segue with the libraries added.
cd $destDir
zip -qr ${segueTag}.zip ${segueTag}